### ISSUE TITLE
DB設計をする。

### ISSUE THREAD

**Issue by NorifumiOgawa** [NorifumiOgawa/gardenscheduler#10]

**Comment by NorifumiOgawa** [comment]
## DB設計

- [Cacoo](https://cacoo.com/diagrams/EpTv60SCjfOYB9sJ/4F461)

<img src='https://user-images.githubusercontent.com/770527/179336631-4ad6fc76-6453-4211-8ef9-99eddaf516be.png'>

※ ユーザー認証にはDeviseを使用し、LINEアカウント連携のみを使用します。
※ 作業写真の保存にはActiveStorageを使用します。

**Comment by u1tnk** [comment]
気になったことを列挙します
- userとscheduleのx0401とはなんでしょう？検索しましたが都道府県コード？？だとするとスケジュールに何故あるのでしょうか？
- 作業予定の時間、作業内容、結果が全部taskにあるように見えます。schedulesのnameには何が入るのでしょうか？というかプロトタイプ見た感じvarietiesとtasksで済みそうですがschedulesはどういう役割があるのでしょうか？
- トップページに「エリア」とあるのですがどこに入っているでしょうか？
- doneは終了フラグで done_dateは終了日が入ると思うのですが、done_dateがの有無で終了が判定できるのでdoneは不要かと思います。
- Railsで実装する予定でしょうか？それであればログとしての日付は `_at`を使う慣習なので `done_date`では無く `done_at`になると思います。
- doneは終了したという意味なので `memo/date/image`のprefixに使うのはちょっと不適切かなと思います。個人的には作業をしたメモという事でwork_memoとか…？imageも将来的にbefore/afterを撮影したりとか拡張される可能性がありますしね。
    - 自作サービスは今後運用していくものなので拡張性も大事です。
- memo/done_memoとありますが、done_memoがあるから memoは作業予定だ思うのですが、が tasks.memo だと何が入っているか分かりづらいのでもうちょっと具体性を上げた名前にしましょう。

**Comment by NorifumiOgawa** [comment]
## 方針
- scheduleにもx0401をもたせる。理由は、userが引っ越した時にスケジュールに影響を与えないため。
- scheduleには１年（サイクル）分の生育スケジュールを入れる。次年分は新たに作る。
- done は不要で、done_atで判断する。
- 全体を見なくても、カラムだけ見れば意味や目的がわかるような命名にすべき。
- done_image、複数持たせるのであれば、done_image1, done_image2, done_image3
-

**Comment by NorifumiOgawa** [comment]
## DB設計(2022/7/24 修正)

修正点
- Tasks の done 削除
- Tasks の done_date を done_at に変更
- Tasks の memo を plan_memo に変更
- Tasks の done_image を done_image1 に変更 ※将来 plan_image* が追加になるかもしれないので、done_image*とした。
- Tasks に done_image2 を追加
![image](https://user-images.githubusercontent.com/770527/180629307-173506e6-3277-4462-b7a6-cb40af5f73ab.png)

**Comment by u1tnk** [comment]
done_image2までできているのは二枚は追加可能にするという事でしょうか？
そうであれば問題無いですが、今必要じゃなかったら追加しなくても大丈夫です。

それ以外は大丈夫です 🙆‍♀️
