### ISSUE TITLE
URI設計

### ISSUE THREAD

**Issue by NorifumiOgawa** [NorifumiOgawa/gardenscheduler#16]

**Comment by NorifumiOgawa** [comment]
Method | Path | Discription
-- | -- | --
GET | / | トップ（品種variety、エリアarea、自分のスケジュール絞り込みmy等のパラメータを持たせる）
  |   |  
GET | /schedules/:id | idのスケジュール詳細、紐づく作業記録表示
GET | /schedules/new | スケジュールの新規作成
GET | /schedules/:id/edit | スケジュール編集
POST | /schedules | スケジュールの登録(create)
PUT | /schedules/:id | スケジュールの更新(update)
DELETE | /schedules/:id | スケジュールの削除
GET | /schedules/ | Myスケジュール（作業予定の近い順一覧表示）
  |   |  
GET | /schedules/:id/logs | 作業記録の新規作成
GET | /logs/:id/edit | 作業記録編集
POST | /logs | 作業記録の登録(create)
PUT | /users/:id | 作業記録の更新(update)
DELETE | /logs/:id | 作業記録の削除
  |   |  
GET | /users/sign_in | LINEアカウント連携、ログイン
DELETE | /users/sign_out | ログアウト
GET | /users/:id | ユーザー詳細、ユーザーのスケジュール一覧
GET | /users/edit | ユーザー情報編集（＋通知時間帯設定）（＝プロフィール設定）
PUT | /users/:id | ユーザー情報の更新(update)
DELETE | /users/:id | ユーザー情報の削除

※LINE通知の時間帯を設定する画面は、ユーザー情報の一項目として持たせるように変更します。

**Comment by NorifumiOgawa** [comment]
- GET | /schedules/ みんなのスケジュール
- GET | /users/:uid/schedules/ ユーザー指定スケジュール
- GET | /my_schedules/ Myスケジュール

**Comment by NorifumiOgawa** [comment]
## URI設計(2022/7/24修正)

Method | Path | Discription
-- | -- | --
GET | / | トップ（登録済みスケジュールの一覧表示をおこなうので、パラメータに品種`variety`、エリア`area`、自分のスケジュール絞り込み`my`等を持たせる）
  |   |  
GET | /schedules/:id | スケジュール詳細(show)(＋紐づく作業記録表示）
GET | /schedules/new | スケジュールの新規作成(new)
GET | /schedules/:id/edit | スケジュール編集(edit)
POST | /schedules | スケジュールの登録(create)
PUT | /schedules/:id | スケジュールの更新(update)
DELETE | /schedules/:id | スケジュールの削除(destroy)
GET | /schedules/ | みんなのスケジュール
GET | /users/:user_id/schedules/ | ユーザー指定スケジュール一覧
  |   |  
GET | /tasks/ | 自分の作業予定（スケジュールをまたがった予定作業一覧表示）
GET | /tasks/:id/edit | 作業記録編集(edit)（=作業記録画面）
PUT | /tasks/:id | 作業記録の更新(update)
DELETE | /tasks/:id | 作業記録の削除(destroy)
  |   |  
GET | /users/sign_in | LINEアカウント連携、ログイン(new)
DELETE | /users/sign_out | ログアウト(destroy)
GET | /users/:id | ユーザー詳細、ユーザーのスケジュール一覧(show)
GET | /users/edit | ユーザー情報編集(edit)（＋通知時間帯設定）（=プロフィール設定）
PUT | /users/:id | ユーザー情報の更新(update)
DELETE | /users/:id | ユーザー情報の削除(destroy)

### 変更点

- 追加） GET | /schedules/ | みんなのスケジュール
- 追加） GET | /users/:user_id/schedules/ | ユーザー指定スケジュール一覧
- 追加） GET | /tasks/ | 自分の作業予定（スケジュール問わず将来の予定作業を一覧表示）
- 削除） POST | /tasks | 作業記録の登録(create) *スケジュール作成・変更時にcreateされる

**Comment by u1tnk** [comment]
良いと思います 👍
